
# Definição dos serviços
services:

  # Configurações do Banco de Dados
  database:
    container_name: Postgres
    image: postgres:alpine
    restart: on-failure
    volumes:
      - ./.pgdata:/var/lib/postgresql
    env_file: 
      - ./config_db/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10





  # Configuração do Backend
  django:
    container_name: Django_REST
    build:
      context: ./backend_api
      dockerfile: Dockerfile
    command: |
      sh -c "
      python manage.py migrate &&
      python manage.py shell -c \"
      from django.contrib.auth import get_user_model
      User = get_user_model()
      if not User.objects.filter(username='filopedia').exists():
          User.objects.create_superuser('filopedia', '', '123123')
      \" &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend_api:/app/
      #- ./crawler:/app/crawler
      - ./data:/app/data
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./config_db/.env



  # Configuração do Frontend
  react:
    container_name: React
    build: 
      context: ./frontend
    volumes: 
      - type: bind
        source: ./frontend
        target: /app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on: 
      - django