# Generated by Django 6.0 on 2026-02-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filosofo",
            name="slug",
            field=models.SlugField(max_length=140),
        ),
    ]
