# Generated by Django 6.0 on 2026-02-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_alter_filosofo_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filosofo",
            name="slug",
            field=models.SlugField(max_length=120),
        ),
    ]
