# Generated by Django 6.0 on 2026-02-17 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_auto_20260214_1350"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exibicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_exibicao", models.DateField(auto_now=True)),
                (
                    "id_filosofo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cards.filosofo"
                    ),
                ),
            ],
        ),
    ]
