# Generated by Django 6.0 on 2026-02-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filosofo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("biografia", models.TextField()),
                ("imagem", models.CharField()),
                ("referencias", models.CharField()),
                ("slug", models.SlugField(max_length=120)),
            ],
        ),
    ]
