# Generated by Django 6.0 on 2026-02-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_alter_filosofo_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="filosofo",
            name="publicado",
            field=models.BooleanField(default=True),
        ),
    ]
