# Generated by Django 6.0 on 2026-02-14 16:50

from django.db import migrations
import os

def carregar_sql():
    caminho = os.path.join(os.path.dirname(__file__), '../insert.sql')
    with open(caminho, 'r', encoding='utf-8') as f:
        return f.read()
    
class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_filosofo_publicado"),
    ]

    operations = [
        migrations.RunSQL(carregar_sql())
    ]
