# Generated by Django 6.0 on 2026-02-17 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0008_alter_exibicao_data_exibicao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exibicao",
            name="data_exibicao",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 2, 17, 13, 33, 8, 146345, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
